openapi: 3.0.1
info:
  title: HelloWorld
  description: API Definition of HelloWorld
  version: 1.0.0
servers:
- url: http://da029ff7-4b16-41ed-bd9e-37e33c702089-dev.e1-us-east-azure.choreoapis.dev/micro-integrator/mi-samples-new/
paths:
  /:
    post:
      responses:
        default:
          description: Default response
